### PR TITLE
Add function to copy BV file sets and update vhdr and vmrk files appropriately

### PR DESCRIPTION
**Pull request by jdkoen**
Creates functionality to copy and rename brain vision file sets. pop_copybv() updates the DataFile and MarkerFile information in the .vhdr and .vmrk files. bv_text_catcher() is a utility function to capture the DataFile and MarkerFile strings, and then update them with the new information.

### CODE REVIEW

**Comment by widmann** [comment]
Thanks for the contribution! The "usage" and "input" parts of the help text of bv_text_catcher.m are incorrect and misleading. Could you please correct? Or preferably, in case the bv_text_catcher function will not also be used in other plugin functions in foreseeable future, make it a nested function within pop_copybv? And add trailing newline at the ends of the files?

Thank you! Best,
Andreas

**Comment by jdkoen** [comment]
Thank you for the feedback. I made the requested changes (bv_text_catcher as a nested function in pop_copybv) and adding trailing newlines at the end of pop_copybv. bv_text_catcher was deleted as a stand alone file, but the help information (which I also updated) is kept with it just in case it requires moving to a stand alone function in the future.

**Comment by widmann** [comment]
Merged. Thanks for the contribution!
Best,
Andreas

**Comment by jdkoen** [comment]
Great news! Thanks for the help.

I have some other ideas that I hope to get too in the future (it will
probably take a while). I’ll reach out to get your input on these changes
when I get around to them (mainly to help me determine if they will be
useful, and if you see any potential drawbacks to the approaches). What is
the best way to communicate about this (GitHub or personal messages)?

Best,

Josh

**Comment by widmann** [comment]
> What is
> the best way to communicate about this (GitHub or personal messages)?
Typically, GitHub is the preferred platform. The development process is documented for future reference and also others can contribute their opinions. The latter might be particularly relevant in case of the writing/export functions which are maintained by Arno. And GitHub has the core advantage that issues/requests remain open until fixed/merged serving as a reminder. Emails tend to slip beyond the email event horizon...

Straight-forward short questions can be discussed by mail  of course.

Best,
Andreas

> Am 26.08.2019 um 18:36 schrieb Josh Koen <notifications@github.com>:
> 
> Great news! Thanks for the help.
> 
> I have some other ideas that I hope to get too in the future (it will
> probably take a while). I’ll reach out to get your input on these changes
> when I get around to them (mainly to help me determine if they will be
> useful, and if you see any potential drawbacks to the approaches). What is
> the best way to communicate about this (GitHub or personal messages)?
> 
> Best,
> 
> Josh
>

**Comment by jdkoen** [comment]
Thanks!

**Pull request merged**
